### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by Bobbbay** [semissioncontrol/semcos#15]

**Comment by ConniTheKiwi** [comment]
Is this reffering to adding libcurl? or the curl cli command

**Comment by Bobbbay** [comment]
@ConniTheKiwi The `curl` command. Would you like me to assign this to you?

**Comment by ConniTheKiwi** [comment]
Not yet as i havnt got a working build of semc

**Comment by Bobbbay** [comment]
Deprecated as of 647e09ce9268854abe284da5d3906e2c1472a5bc
