### ISSUE TITLE
Seems like startup scripts aren't being run

### ISSUE THREAD

**Issue by Bobbbay** [semissioncontrol/semcos#19]
They're supposed to spit out some `[OK]` responses on boot, but it seems like they don't run, Furthermore, the custom startup scrupts do run (because they're triggered vy `/etc/rc.d/startup`) 🤔. I think I'll try running them from `/etc/rc.d/startup`, seems like right way.

**Comment by Bobbbay** [comment]
Potentially fixed in semcos-packages/etc@d59bea751d7ba2821539300412576baa607f09a0.

**Comment by Bobbbay** [comment]
It's worse than I thought - the CLFS bootscripts are completely incorrect. Found the right ones though!

**Comment by ConniTheKiwi** [comment]
I believe when i run my tests that i saw them [OK] Outputs, has this issue been resolved?

**Comment by Bobbbay** [comment]
I had indeed solved this, but it remains open because of #21.

**Comment by Bobbbay** [comment]
Closed thanks to #7
