### ISSUE TITLE
Fix `/dev` not exiting problem

### ISSUE THREAD

**Issue by Bobbbay** [semissioncontrol/semcos#21]
Seems like `mkdir /dev` does the trick - gotta get that in somehow, as git doesn't track empty directories.

**Comment by Bobbbay** [comment]
`proc, media/{floppy,cdrom}, srv, sys, tmp, install -dv -m 1777 {var,}/tmp` is a summary of everything that should be created - interestingly enough, seems like this still isn't working for me...

**Comment by ConniTheKiwi** [comment]
Where do you run mkdir?

**Comment by Bobbbay** [comment]
I have my initial Gentoo system, onto which I boot, mount /dev/sda8 /mnt, and mkdir /mnt/dev.

**Comment by Bobbbay** [comment]
Closed due to #7
