### ISSUE TITLE
Quantum Support

### ISSUE THREAD

**Issue by RhinoCodes** [semissioncontrol/semcos#30]
Quantum is the package manager for SEMC OS, up untill now it has not run out of the box, and it still doesn't, but there is a way to do it...

Run the following commands from your host machine:
`sudo cp -r /usr/lib64/*sqlite* /mnt/semcos/usr/lib64/`
`sudo cp -r /usr/lib64/*icui* /mnt/semcos/usr/lib64/`
`sudo cp -r /usr/lib64/*icuuc* /mnt/semcos/usr/lib64/`
`sudo cp -r /usr/lib64/*icudata* /mnt/semcos/usr/lib64/`
And after installing the lua dev packages on your system:
`sudo cp -r /usr/lib64/*lua* /mnt/semcos/usr/lib64`

Then you can compile Quantum on your host machine and transfer the binary to the SEMC OS system, compiling on SEMC OS not tested

**Comment by Bobbbay** [comment]
I mean, that is pretty bad, you don't want to just copy so files without the libraries. `*` matches many things but not everything. What we really want to do is install the packages in the bootstrapper, and eventually in the Qt installer. Take a look at [how we install busybox](https://github.com/semissioncontrol/semcos/blob/development/bin/semcos#L425-L441) in the bootstrapper. Everything, for example sqlite, should be installed from source, this way we make sure nothing is corrupt or half-installed. Try writing a PR to the bootstrapper!

**Comment by RhinoCodes** [comment]
Yes, this is just a hacky way to get it working for now lol

**Comment by Bobbbay** [comment]
A hacky way is not a full way 😄 

I'll bother people a ton for this, but that simply does not work.

**Comment by RhinoCodes** [comment]
@Bobbbay this was just a way to get it working for a bit, I will start working on the PR

**Comment by Bobbbay** [comment]
Deprecated as of 647e09ce9268854abe284da5d3906e2c1472a5bc
